### PR TITLE
feedback

### PR DESCRIPTION
**Pull request by anon1911**
Adding some feedback. I've added separate commits with modifications that you could more easily navigate through.

### CODE REVIEW

**Review by TreusK — COMMENTED** [review]
That sounds like I'll confuse the names down the line eventually tho, I hate giving props different names than what I'm passing
Also comments are not commit individual? Then Ill guess ill write everything here.
Well now the moving stuff below app from the anime search makes sense, I always just declare everything inside the components, will do that from now on.
Mm really I just used nanoid because the no key warning was annoying.
Ah yeah using required would take care of that check.
I hate buttons! They're annoying to style and are weird, while divs are cool, flat and squarey and do whatever you tell them to. 

See these are way easier than the anime search ones! And i even changed tab to 2 spaces so even prettify has a lighter load

**Comment by anon1911** [comment]
> I hate buttons! They're annoying to style and are weird, while divs are cool, flat and squarey and do whatever you tell them to.

Since you're using Tailwind, it includes a CSS reset which should reset all the styles for buttons essentially removing all built-in browser styling for them. The benefits using Buttons over divs with onClick handlers is that you have:

1. Keyboard focus
2. Keyboard interaction with space and enter

These two alone are much more worth it and makes your app usable with just a keyboard

**Comment by anon1911** [comment]
>That sounds like I'll confuse the names down the line eventually tho, I hate giving props different names than what I'm passing

I'm assuming you're referring to `onXXX` vs `handleXXX` - the reason why I prefer using `onXXX` for props is because there's a difference between events and event handlers. `onXXX` should strictly refer to the event that the component can invoke, while `handleXXX` should refer to the actual function that's handling the event. For example:

```jsx
function App() {
  return <form onClick={handleClick} onMouseDown={handleMouseDown} onSubmit={handleSubmit} />
}
```

We know from the above code snippet that the form can invoke three different events, but if we were to rename those props `handleClick`, `handleMouseDown` & `handleSubmit`, it's now extremely unclear that the form element would actually invoke those events.

**Comment by TreusK** [comment]
I changed the handles to ons and moved the helpers out :)
Now let me close this because I'm trying to add a branch and it's giving me an error, let's see if it was this

**Comment by TreusK** [comment]
It wasn't this
It was the upstream thingy
Which I ignored so I hope everything works

**Pull request closed without merging**
